version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: 'sentry*'

  - package-ecosystem: 'npm'
    directory: '/apps/enterprise'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: 'sentry*'

  - package-ecosystem: 'npm'
    directory: '/apps/org-settings'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: 'sentry*'
