fix: ['fix/*', 'bugfix/*', 'hotfix/*']
feat: ['feat/*', 'feature/*']
chore: ['chore/*']
docs: ['docs/*']
test: ['test/*']
perf: ['perf/*']
style: ['style/*']
refactor: ['refactor/*']
build: ['build/*']
ci: ['ci/*']
