name: static-checks
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'

      - name: 'Install node modules'
        run: 'yarn install'
      - name: Check typescript
        run: yarn ts-check
      - name: Check linting
        run: yarn lint
